#!/bin/bash

# chkconfig: - 85 15
#this script for start|stop rsync daemon service 
#date:2012/2/13 
 
status=$(netstat -lnp | grep -w 873 | grep -v 'grep') 
pidfile="/var/run/rsyncd.pid" 
start_rsync="rsync --daemon"
pid=$(ps -ef | egrep "rsync --daemon"  | grep -v 'grep' | gawk -F' '  '{print $2}')

 
function rsyncstart() { 
 
    if [ "${status}X" == "X" ];then 
       ${start_rsync}   
       
        status=$(netstat -lnp | grep -w 873 | grep -v 'grep') 
  
        if [  "${status}X" != "X"  ];then 
             
            echo "rsync service start.......OK" 
             
        fi 
 
    else 
 
        echo "rsync service is running !"    
 
    fi 
} 
 
function rsyncstop() { 
 
    if [ "${status}X" != "X" ];then 
     
        kill -9 ${pid}
        rm -f $pidfile     
        status=$(netstat -lnp | grep -w 873 | grep -v 'grep') 
         
        if [ "${status}X" == "X" ];then 
             
            echo "rsync service stop.......OK" 
        fi 
    else 
 
        echo "rsync service is not running !"    
 
    fi 
} 
 
 
function rsyncstatus() { 
 
 
    if [ "${status}X" != "X" ];then 
 
        echo "rsync service is running !"   
     
    else 
 
         echo "rsync service is not running !"  
 
    fi 
 
} 
 
function rsyncrestart() { 
 
    if [ "${status}X" == "X" ];then 
 
               echo "rsync service is not running..." 
 
               rsyncstart 
        else 
 
               rsyncstop 
 
               rsyncstart    
 
        fi       
}  
 
case $1 in 
 
        "start") 
               rsyncstart 
                ;; 
 
        "stop") 
               rsyncstop 
                ;; 
 
        "status") 
               rsyncstatus 
               ;; 
 
        "restart") 
               rsyncrestart 
               ;; 
 
        *) 
          echo 
                echo  "Usage: $0 start|stop|restart|status" 
          echo 
esac 
